- id: '1508100387389'
  alias: 'Notification: Sheila is Home'
  trigger:
  - entity_id: person.sheila
    from: not_home
    platform: state
    to: home
  condition: []
  action:
    data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sheila is Home
      title: Home Assistant
    service: notify.mobile_app_sm_g986u
- id: '1508111230955'
  alias: 'Notification: Sheila is Away'
  trigger:
  - entity_id: person.sheila
    from: home
    platform: state
    to: not_home
  condition: []
  action:
    data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sheila is Away
      title: Home Assistant
    service: notify.mobile_app_sm_g986u
- id: '1508112507193'
  alias: Turn off TV when nobody is home
  trigger:
  - entity_id: group.family
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      activity: '-1'
      entity_id: remote.living_room
    service: remote.turn_on
- id: '1359112557492'
  alias: Denon Set Volume
  trigger:
  - entity_id: input_number.denon_volume
    platform: state
  condition:
  - condition: template
    value_template: '{{ states(''sensor.denon_volume'') != states(''input_number.denon_volume'')
      }}'
  action:
  - data: {}
    service: rest_command.set_volume
- id: '1278239414347'
  alias: Denon Get Volume
  trigger:
  - entity_id: sensor.denon_volume
    platform: state
  action:
  - data_template:
      entity_id: input_number.denon_volume
      value: '{{ states.sensor.denon_volume.state | float }}'
    service: input_number.set_value
- id: '1519263645671'
  alias: 'Notification: Trash Pick-up'
  trigger:
  - entity_id: group.matt
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sensor.trash_pickup_tomorrow
    state: 'true'
  - condition: state
    entity_id: sensor.recycling_pickup_tomorrow
    state: 'false'
  action:
  - data:
      data:
        icon: https://goo.gl/xeetdy
        vibration: 0,65,706,86,657,95,668,100
      message: Trash pick-up is tomorrow
      title: Home Assistant
    service: notify.mobile_app_sm_g986u
- id: '1519263819689'
  alias: 'Notification: Recycling Pick-up'
  trigger:
  - entity_id: person.matt
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sensor.recycling_pickup_tomorrow
    state: 'true'
  action:
  - data:
      data:
        icon: https://goo.gl/xeetdy
        vibration: 0,65,706,86,657,95,668,100
      message: Trash and Recycling pick-up is tomorrow
      title: Home Assistant
    service: notify.mobile_app_sm_g986u
- action:
  - data_template:
      entity_id: input_select.remote
      option: '{{ states.remote.living_room.attributes.current_activity }}'
    service: input_select.select_option
  alias: Remote - Update Input Select from External Source
  condition: []
  id: '1519349569120'
  trigger:
  - entity_id: remote.living_room
    platform: state
- action:
  - service: script.input_select_harmony
  alias: Remote - Start Activity from Input Select
  condition: []
  id: '1519586698231'
  trigger:
  - entity_id: input_select.remote
    platform: state
- action:
  - data:
      entity_id: cover.double
    service: cover.open_cover
  alias: CarPresenceMatt_on
  condition:
  - condition: state
    entity_id: cover.double
    state: closed
  id: '1525289140121'
  trigger:
  - entity_id: binary_sensor.mattcar
    from: 'off'
    platform: state
    to: 'on'
- id: '1525289339211'
  alias: CarPresenceMatt_off
  trigger:
  - entity_id: binary_sensor.mattcar
    for: 0:60:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: cover.double
    state: open
  action:
  - data:
      entity_id: cover.double
    service: cover.close_cover
- id: '1534627488910'
  alias: Cert Expiry Warning
  trigger:
  - below: '21'
    entity_id: sensor.ssl_certificate_expiry
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org/hassio/dashboard
      message: Home Assistant cert will expire in {{ states.sensor.ssl_certificate_expiry.state
        }} days
      title: Hassio Cert Warning
    service: notify.mobile_app_sm_g986u
- id: '1536003304002'
  alias: 'Notification Handler: Close Garage Door Notification Clicked'
  trigger:
  - event_data:
      action: toggle_door
    event_type: mobile_app_notification_action
    platform: event
  condition: []
  action:
  - data:
      entity_id: cover.double
    service: cover.open_cover
- id: '1536003653612'
  alias: 'Notification: Close the Garage Door?'
  trigger:
  - entity_id: binary_sensor.mattcar
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.double
    state: open
  action:
  - data:
      data:
        actions:
        - action: toggle_door
          title: Close Garage Door
      message: Close the garage door?
    service: notify.mobile_app_sm_g986u
- id: '1537368791217'
  alias: Partial Backup Creation
  trigger:
  - at: '3:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - data:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_partial
  - data:
      data:
        url: https://cfautomation.duckdns.org/
      message: Automated Backup {{ now().strftime('%Y-%m-%d') }} Created
      title: Automated Backup
    service: notify.mobile_app_sm_g986u
- id: '1537369552014'
  alias: Partial Backup Upload
  trigger:
  - at: '4:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      data:
        url: https://cfautomation.duckdns.org/
      message: Automated Backup Pushed to Dropbox
      title: Automated Backup
    service: notify.mobile_app_sm_g986u
- id: '1538361242918'
  alias: Server Status Sabnzbd
  trigger:
  - entity_id: sensor.sabnzbd
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sabnzbd Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361347240'
  alias: Server Status Plex
  trigger:
  - entity_id: sensor.plex
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Plex Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361402330'
  alias: Server Status Radarr
  trigger:
  - entity_id: sensor.radarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Radarr Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361466349'
  alias: Server Status Sonarr
  trigger:
  - entity_id: sensor.sonarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sonarr Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361518875'
  alias: Server Status Organizr
  trigger:
  - entity_id: sensor.organizr
    from: 'ON'
    platform: state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Organizr Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361573324'
  alias: Server Status Freenas
  trigger:
  - entity_id: sensor.freenas
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Freenas Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1538361615074'
  alias: Server Status DNS
  trigger:
  - entity_id: sensor.dns
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: DNS Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1539735543513'
  alias: Server Status Lidarr
  trigger:
  - entity_id: sensor.lidarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Lidarr Service is down
      title: Server Status Notification
    service: notify.mobile_app_sm_g986u
- id: '1525291938220'
  alias: 'Notification: Garage Door Left Open'
  trigger:
  - entity_id: cover.double
    for: 00:15:00
    platform: state
    to: Open
  condition: []
  action:
  - data:
      data:
        actions:
        - action: toggle_door
          title: Close Garage Door
      message: Garage door was left open!
    service: notify.mobile_app_sm_g986u
- id: '1549846583175'
  alias: 'Notification: Freezer Temp Warning'
  trigger:
  - above: '15'
    entity_id: sensor.shelly_ht_temp
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Freezer Temperature is above 15 degrees
      title: Freezer Temp Warning
    service: notify.mobile_app_sm_g986u
  - data:
      message: 'Automated Message: Freezer Temperature is above 15 degrees!'
      number: '6189788691'
    service: notify.mobile_app_sm_g986u
- id: '1570930192329'
  alias: Auto Renew SSL Cert
  trigger:
  - below: '25'
    entity_id: sensor.ssl_certificate_expiry
    platform: numeric_state
  condition: []
  action:
  - service: shell_command.renew_ssl
- id: '1570930944748'
  alias: 'Notification: Shelly Temp Sensor Battery Warning'
  trigger:
  - below: '15'
    entity_id: sensor.shelly_ht_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org/hassio/dashboard
      message: Shelly Temp Sensor Battery is at {{ states.sensor.shelly_ht_battery.state
        }}%
      title: Battery Warning
    service: notify.mobile_app_sm_g986u
- id: '1571266818491'
  alias: 'Notification: Alexis home from school'
  description: Sends a text whenever Alexis gets home from school
  trigger:
  - entity_id: person.alexis
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: '15:00:00'
    before: '17:00:00'
    condition: time
  action:
  - data:
      message: 'Automated Message: Alexis is home from school'
      number: '6189788691'
    service: joaoapps_join.mattgs9_send_sms
  - data:
      data:
        actions:
        - action: toggle_door
          title: Open Garage Door
      message: Welcome Home Alexis
    service: notify.mobile_app_sm_j337v
- id: '1571495208036'
  alias: Set theme at startup
  description: Sets the HA theme to "Slate" at startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
