- id: '1508100387389'
  alias: Sheila is Home
  trigger:
  - entity_id: device_tracker.sheila_phone
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - alias: Pushover
    data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sheila is Home
      title: Home Assistant
    service: notify.google_cloud_messaging_matts_phone
- id: '1508111230955'
  alias: Sheila is Away
  trigger:
  - entity_id: device_tracker.sheila_phone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - alias: Pushover
    data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sheila is Away
      title: Home Assistant
    service: notify.google_cloud_messaging_matts_phone
- id: '1508112507193'
  alias: Family Away
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Nobody is Home
      title: Home Assistant
    service: notify.google_cloud_messaging_matts_phone
  - data:
      entity_id: remote.living_room
    service: remote.turn_off
- id: '1359112557492'
  alias: Denon Set Volume
  trigger:
  - entity_id: input_number.denon_volume
    platform: state
  action:
  - data: {}
    service: rest_command.set_volume
- id: '1278239414347'
  alias: Denon Get Volume
  trigger:
  - entity_id: sensor.denon_volume
    platform: state
  action:
  - data_template:
      entity_id: input_number.denon_volume
      value: '{{ states.sensor.denon_volume.state | float }}'
    service: input_number.set_value
- id: '1518361748860'
  alias: Denon Lower Volume
  trigger:
  - entity_id: sensor.denon_volume
    platform: state
  condition:
  - above: '80'
    condition: numeric_state
    entity_id: sensor.denon_volume
  action:
  - delay: '5'
  - alias: ''
    data: {}
    service: rest_command.volume_correct
- id: '1519263645671'
  alias: 'Reminder: Trash Pick-up'
  trigger:
  - entity_id: device_tracker.google_maps_111946808163369851965
    platform: state
    to: home
  condition:
  - condition: template
    value_template: "{%- set pickupday = strptime(states.calendar.trash_pick_up.attributes.start_time,\
      \ \"%Y-%m-%d %H:%M:%S\").strftime(\"%Y-%m-%d\") -%}\n{%- if pickupday.split(\"\
      -\")[2] | int -1 == states.sensor.date.state.split(\"-\")[2] | int -%}\n   \
      \             true\n              {%- endif -%}"
  - condition: template
    value_template: "{%- set pickupday = strptime(states.calendar.recycling_pick_up.attributes.start_time,\
      \ \"%Y-%m-%d %H:%M:%S\").strftime(\"%Y-%m-%d\") -%}\n{%- if pickupday.split(\"\
      -\")[2] | int -1 == states.sensor.date.state.split(\"-\")[2] | int -%}\n   \
      \             false\n              {%- endif -%}"
  action:
  - data:
      data:
        icon: https://goo.gl/xeetdy
        vibration: 0,65,706,86,657,95,668,100
      message: Trash pick-up is tomorrow
      title: Home Assistant
    service: notify.google_cloud_messaging_matts_phone
- id: '1519263819689'
  alias: 'Reminder: Recycling Pick-up'
  trigger:
  - entity_id: device_tracker.google_maps_111946808163369851965
    platform: state
    to: home
  condition:
  - condition: template
    value_template: "{%- set pickupday = strptime(states.calendar.recycling_pick_up.attributes.start_time,\
      \ \"%Y-%m-%d %H:%M:%S\").strftime(\"%Y-%m-%d\") -%}\n{%- if pickupday.split(\"\
      -\")[2] | int -1 == states.sensor.date.state.split(\"-\")[2] | int -%}\n   \
      \             true\n              {%- endif -%}"
  action:
  - data:
      data:
        icon: https://goo.gl/xeetdy
        vibration: 0,65,706,86,657,95,668,100
      message: Trash and Recycling pick-up is tomorrow
      title: Home Assistant
    service: notify.google_cloud_messaging_matts_phone
- action:
  - data_template:
      entity_id: input_select.remote
      option: '{{ states.remote.living_room.attributes.current_activity }}'
    service: input_select.select_option
  alias: Remote - Update Input Select from External Source
  condition: []
  id: '1519349569120'
  trigger:
  - entity_id: remote.living_room
    platform: state
- action:
  - service: script.input_select_harmony
  alias: Remote - Start Activity from Input Select
  condition: []
  id: '1519586698231'
  trigger:
  - entity_id: input_select.remote
    platform: state
- action:
  - data:
      entity_id: cover.double
    service: cover.open_cover
  alias: CarPresenceMatt_on
  condition:
  - condition: state
    entity_id: cover.double
    state: closed
  id: '1525289140121'
  trigger:
  - entity_id: binary_sensor.mattcar
    from: 'off'
    platform: state
    to: 'on'
- id: '1525289339211'
  alias: CarPresenceMatt_off
  trigger:
  - entity_id: binary_sensor.mattcar
    from: 'on'
    platform: state
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: cover.double
    state: open
  action:
  - data:
      entity_id: cover.double
    service: cover.close_cover
- id: '1525291938220'
  alias: Garage Door Left Open at Night
  trigger:
  - minutes: /5
    platform: time
    seconds: 0
  condition:
  - condition: state
    entity_id: cover.double
    state: open
  - after: sunset
    condition: sun
  action:
  - data:
      data:
        actions:
        - action: close
          icon: /static/icons/favicon-192x192.png
          title: Garage Door Notification
        - action: close_door
          title: Close door
      message: Garage Door was left open at night
    service: notify.google_cloud_messaging_matts_phone
- id: '1534627488910'
  alias: Cert Expiry Warning
  trigger:
  - below: '83'
    entity_id: sensor.ssl_certificate_expiry
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org/hassio/dashboard
      message: Home Assistant cert will expire in {{ states.sensor.ssl_certificate_expiry.state
        }} days
      title: Hassio Cert Warning
    service: notify.google_cloud_messaging_matts_phone
- id: '1535922305145'
  alias: Shopping Notification
  trigger:
  - entity_id: device_tracker.google_maps_111946808163369851965
    event: enter
    platform: zone
    zone: zone.neighborhood_market
  - entity_id: device_tracker.google_maps_111946808163369851965
    event: enter
    platform: zone
    zone: zone.walmart
  condition: []
  action:
  - data:
      data:
        renotify: '0'
        tag: Shopping Notifiation
        url: https://cfautomation.duckdns.org/shopping-list
        vibrate:
        - 300
        - 100
        - 400
      message: I've sent you a shopping list
      title: Shopping List
    service: notify.google_cloud_messaging_matts_phone
- id: '1536003304002'
  alias: HTML5 Garage Door Notification Clicked
  trigger:
  - event_data:
      action: close_door
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      entity_id: cover.double
    service: cover.open_cover
- id: '1536003653612'
  alias: Html5 Notification to Close the Garage Door
  trigger:
  - entity_id: binary_sensor.mattcar
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.double
    state: open
  action:
  - data:
      data:
        actions:
        - action: close
          icon: /static/icons/favicon-192x192.png
          title: Open Home Assistant
        - action: close_door
          title: Close door
      message: Should I Close the Garage Door?
    service: notify.google_cloud_messaging_matts_phone
- id: '1537368791217'
  alias: Partial Backup Creation
  trigger:
  - at: '3:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - data:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_partial
  - data:
      data:
        url: https://cfautomation.duckdns.org/
      message: Automated Backup {{ now().strftime('%Y-%m-%d') }} Created
      title: Automated Backup
    service: notify.google_cloud_messaging_matts_phone
- id: '1537369552014'
  alias: Partial Backup Upload
  trigger:
  - at: '4:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
  - data:
      data:
        url: https://cfautomation.duckdns.org/
      message: Automated Backup Pushed to Dropbox
      title: Automated Backup
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361242918'
  alias: Server Status Sabnzbd
  trigger:
  - entity_id: sensor.sabnzbd
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sabnzbd Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361347240'
  alias: Server Status Plex
  trigger:
  - entity_id: sensor.plex
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Plex Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361402330'
  alias: Server Status Radarr
  trigger:
  - entity_id: sensor.radarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Radarr Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361466349'
  alias: Server Status Sonarr
  trigger:
  - entity_id: sensor.sonarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Sonarr Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361518875'
  alias: Server Status Organizr
  trigger:
  - entity_id: sensor.organizr
    from: 'ON'
    platform: state
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Organizr Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361573324'
  alias: Server Status Freenas
  trigger:
  - entity_id: sensor.freenas
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Freenas Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1538361615074'
  alias: Server Status DNS
  trigger:
  - entity_id: sensor.dns
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: DNS Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
- id: '1539735543513'
  alias: Server Status Lidarr
  trigger:
  - entity_id: sensor.lidarr
    platform: state
    to: 'OFF'
  condition: []
  action:
  - data:
      data:
        url: https://cfautomation.duckdns.org
      message: Lidarr Service is down
      title: Server Status Notification
    service: notify.google_cloud_messaging_matts_phone
