homeassistant:  
  customize: !include customize.yaml


#removing default_config and enebling only what i want
#default_config:
automation: !include automations.yaml
cloud:
config:
frontend:
  extra_html_url:
    - /local/custom_ui/custom-weather-card.html
  extra_html_url_es5:
    - /local/custom_ui/custom-weather-card.html
  themes: !include includes/themes.yaml
  javascript_version: latest
history:
logbook:
#map:
mobile_app:
person:
script: !include scripts.yaml
ssdp:
sun:
system_health:
updater:
zeroconf:
#zone: !include includes/zone.yaml
#end default_config

google_assistant: !include includes/google_assistant.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: False
  login_attempts_threshold: 5
discovery:
conversation:
shopping_list:
timer: !include includes/timer.yaml
sensor: !include_dir_merge_list includes/sensor/
binary_sensor: !include includes/binary_sensor.yaml
weather: !include includes/weather.yaml
camera: !include includes/camera.yaml
remote: !include includes/remote.yaml
device_tracker: !include includes/device_tracker.yaml
notify: !include includes/notify.yaml
google: !include includes/google.yaml
input_number: !include includes/input_number.yaml
rest_command: !include includes/rest_command.yaml
cover: !include includes/cover.yaml
media_player: !include includes/media_player.yaml
joaoapps_join: !include includes/joaoapps_join.yaml
recorder: !include includes/recorder.yaml
shell_command: !include includes/shell_command.yaml
switch: !include includes/switch.yaml
group: !include includes/group.yaml

